name: Continuous Deployment

on:
  push:
    branches:
      - main
      - feature/*
      - hotfix/*

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: "5.2.x"

      - name: Get version number
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.4
        with:
          useConfigFile: "true"
          configFilePath: "${{ github.workspace }}/gitversion.yml"

      - name: Set shared variables
        run: |
          echo ::set-env name=IS_PRE_RELEASE::${{ github.ref != 'refs/heads/main' }}

      - name: Set environment to test
        if: env.IS_PRE_RELEASE == 'true'
        run: |
          echo ::set-env name=ENVIRONMENT::test

      - name: Set environment to live
        if: env.IS_PRE_RELEASE == 'false'
        run: |
          echo ::set-env name=ENVIRONMENT::live

      - name: Output variables
        run: |
          echo Environment: ${{ env.ENVIRONMENT }}
          echo Pre-release: ${{ env.IS_PRE_RELEASE }}
          echo Version: v${{ steps.gitversion.outputs.SemVer }}
          echo Branch name: ${{ steps.gitversion.outputs.EscapedBranchName }}
          echo InformationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}
          echo FullBuildMetaData: ${{ steps.gitversion.outputs.FullBuildMetaData }}
