name: CI

on:
  # Pushes will trigger a package build for pre-release
  # Pull requests will trigger a package build for production
  push:
    branches:
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main

env:
  IS_PRERELEASE: ${{ github.event_name == 'push' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: "5.2.x"

      - name: Get version number
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.4
        with:
          useConfigFile: "true"
          configFilePath: "${{ github.workspace }}/gitversion.yml"

      - name: Set environment variables based on target branch
        run: |
          echo ::set-env name=COMMIT_MESSAGE::$(git log -1 HEAD --pretty=format:%s)

      - name: Archive Output
        uses: thedoctor0/zip-release@master
        with:
          filename: release.zip
          path: src/**/*

      - name: Update Release
        id: update_release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release.zip
          release: v${{ steps.gitversion.outputs.SemVer }}
          tag: v${{ steps.gitversion.outputs.SemVer }}
          body: |
            Version: v${{ steps.gitversion.outputs.SemVer }}
            Branch name: ${{ steps.gitversion.outputs.EscapedBranchName }}

            InformationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}
            FullBuildMetaData: ${{ steps.gitversion.outputs.FullBuildMetaData }}

            Changes:
            - ${{ env.COMMIT_MESSAGE }}
          prerelease: ${{ env.IS_PRERELEASE }}
          draft: true
