name: "CD Pre-Release"

on:
  release:

env:
  IS_PRERELEASE: ${{ github.event.release.prerelease }}

jobs:
  release:
    if: github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
